use std::fs::File;

use gds_engine_rust::oasis_loader::load_oasis;

fn find_top(lib: &gds_engine_rust::geometry::Library) -> &gds_engine_rust::geometry::Cell {
    lib.cells.iter().find(|c| c.name == "TOP").expect("TOP cell present")
}

fn assert_points_close(
    got: &[gds_engine_rust::geometry::Point],
    expected: &[(f64, f64)],
    eps: f64,
) {
    assert_eq!(got.len(), expected.len(), "point count mismatch");
    for (i, (g, (ex, ey))) in got.iter().zip(expected.iter()).enumerate() {
        assert!(
            (g.x - ex).abs() <= eps && (g.y - ey).abs() <= eps,
            "point[{i}] mismatch: got=({}, {}), expected=({}, {})",
            g.x,
            g.y,
            ex,
            ey
        );
    }
}

#[test]
fn ctrapezoid_type0_roundtrips_from_oas_fixture() {
    let file = File::open("tests/generated/ctrapezoid_type0.oas").expect("open fixture");
    let lib = load_oasis(file).expect("load oas");
    let cell = find_top(&lib);

    assert_eq!(cell.polygons.len(), 1, "expected one polygon");
    let poly = &cell.polygons[0];
    assert_eq!(poly.layer, 1);
    assert_eq!(poly.datatype, 0);

    // Generated by gdstk from a trapezoid polygon. This must NOT get simplified
    // to a rectangle during CTRAPEZOID decoding.
    let expected = [(0.0, 0.0), (10.0, 0.0), (7.0, 3.0), (0.0, 3.0)];
    assert_points_close(&poly.points, &expected, 1e-9);
}

#[test]
fn ctrapezoid_type16_triangle_roundtrips_from_oas_fixture() {
    let file = File::open("tests/generated/ctrapezoid_type16.oas").expect("open fixture");
    let lib = load_oasis(file).expect("load oas");
    let cell = find_top(&lib);

    assert_eq!(cell.polygons.len(), 1, "expected one polygon");
    let poly = &cell.polygons[0];
    assert_eq!(poly.layer, 1);
    assert_eq!(poly.datatype, 0);

    let expected = [(20.0, 0.0), (25.0, 0.0), (20.0, 5.0)];
    assert_points_close(&poly.points, &expected, 1e-9);
}
